### ISSUE TITLE
Previous eventHandler being deleted in setSecurityManagerEventHandler

### ISSUE THREAD

**Issue by donatieng** [paul-szczepanek-arm/mbed-os#14]
What's the rationale behind this? I don't think it should be assumed that the event handler is allocated on the heap (and ownership passed to the SecurityManager class).
Also when passed NULL, this method should revert to the default handler.

https://github.com/paul-szczepanek-arm/mbed-os/blob/55045010d60d806bdda05cb132980df881fa88c1/features/FEATURE_BLE/ble/SecurityManager.h#L838-L851

**Comment by paul-szczepanek-arm** [comment]
yep, no argument there
